embeddings:
  path: sentence-transformers/all-MiniLM-L6-v2
  backend: qdrant.Qdrant
  metric: cosine # allowed values: l2 / cosine / ip
  qdrant:
    host: localhost
    port: 6333
    grpc_port: 6334
    prefer_grpc: true
    collection: CustomCollectionName1
    hnsw:
      m: 8
      ef_construct: 256
      full_scan_threshold:
      ef_search: 512